# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EbGt03b8MV3TX67Cf_NQCfBCpKQbo0jW
"""

x = str(input("signal"))
if x == "green":
  print("go")
elif x == "yellow":
  print("get ready")
else:
  print("stop")

x = int(input("enter your number"))
i = 0
for x in range(i, x+1, 4):
  print(x)

x = int(input("age"))
if x >= 18:
  print("elegible to vote")
else:
  print("not elegible to vote")

x = int(input("number"))
if x < 0:
  print("negative number")
else:
  print("positive number")

x = int(input("number"))
if x < 10:
  print("single digit")
elif x < 100:
  print("double digit")
elif x < 1000:
  print("trible digit")
else:
  print("four digit")

x = int(input("number"))
if x % 3 == 0:
  print("divisible by 3")
else:
  print("not divisible by 3")